export type {
  EnemyBehaviorMetrics,
  HarnessPlayerPolicy,
  ItemEvaluationMetrics,
  MapFloorGenerationRecord,
  MockReviewScoreInput,
  LlmPlayerPersona,
  PlacementShortfall,
  PlaythroughScorecard,
  PlaythroughTrace,
  PolicyDecision,
  ProblemRunCategory,
  ProblemRunCategoryKind,
  ProblemRunDiagnostics,
  ScorecardReviewInput,
  StateSummary,
  TacticalDepthMetrics,
  TraceDecisionMetadata,
  TraceMetadata,
  TraceStep,
} from './types.js';
export {
  BASELINE_POLICY_IDS,
  isBaselinePolicyId,
  isLlmPlayerPersona,
  resolveBaselinePolicy,
  type BaselinePolicyId,
  type HarnessPolicyId,
} from './policy-registry.js';
export { LLM_PLAYER_PERSONA_IDS } from './types.js';
export {
  createLlmPlayerPolicy,
  findAvailableActionById,
  parseLlmPlayerModelOutput,
  resolveAvailableActionFromModel,
  resolveLlmPlayerDecision,
  type CreateLlmPlayerPolicyOptions,
  type LlmPlayerClient,
  type LlmPlayerClientResponse,
  type LlmPlayerModelOutput,
  type ResolveAvailableActionResult,
} from './llm-player.js';
export { buildLlmPlayerModelInput, buildLlmPlayerPrompt, type LlmPlayerModelInput } from '../agents/prompts/llm-player.js';
export { buildLlmReviewerModelInput, buildLlmReviewerPrompt, type LlmReviewerModelInput } from '../agents/prompts/llm-reviewer.js';
export {
  assertRealLlmRunAllowed,
  createPersonaPolicyForRun,
  createReviewerForRun,
  isRealLlmRunRequested,
  type RunVersionLlmOptions,
} from './llm-run-options.js';
export {
  createLlmPlayerClientFromChat,
  createLlmPlayerClientFromConfig,
  createOpenAiCompatibleChatClient,
  type LlmChatCompletionClient,
  type LlmChatCompletionRequest,
} from './llm-provider.js';
export {
  LLM_API_KEY_ALT_ENV,
  LLM_API_KEY_ENV,
  LLM_BASE_URL_ENV,
  LLM_MODEL_ENV,
  DEFAULT_LLM_BASE_URL,
  DEFAULT_LLM_MODEL,
  LlmCredentialsMissingError,
  hasLlmProviderCredentials,
  requireLlmProviderConfig,
  resolveLlmProviderConfig,
  type LlmCredentialResolution,
  type LlmProviderConfig,
} from './llm-provider-config.js';
export {
  createLlmReviewerProvider,
  parseLlmReviewerModelOutput,
  resolveLlmReview,
  type LlmReviewGenerationMetadata,
  type LlmReviewerFallbackReason,
  type PlaythroughReviewWithMetadata,
} from './llm-reviewer.js';
export { parseHarnessLlmCliArgs, type HarnessLlmCliArgs } from './cli-args.js';
export { runPlaythrough, parseSimulateSeedArgs, type RunPlaythroughOptions } from './runner.js';
export { deriveScorecardFromTrace, validateScorecard } from './scorecard.js';
export {
  buildMapGenerationMetadata,
  buildPlacementShortfalls,
  buildTraceMetadata,
  collectBalanceProblemCategories,
  collectBalanceProblemReasons,
  deriveEnemyBehaviorMetrics,
  deriveItemEvaluationMetrics,
  deriveProblemRunDiagnostics,
  deriveTacticalDepthMetrics,
  finalizeTraceMetadata,
  isBalanceProblemRun,
} from './trace-diagnostics.js';
export { stringifyDeterministicJson } from './json.js';
export {
  ARTIFACT_WRITE_MODES,
  DEFAULT_ARTIFACT_WRITE_MODE,
  archiveExistingFile,
  assertArtifactWritable,
  buildArchiveDestination,
  fileExists,
  parseArtifactWriteMode,
  resolveVersionId,
  writeArtifactFile,
  VERSION_ID_ALIAS_ENTRIES,
  type ArtifactWriteMode,
  type ArtifactWriteOptions,
  type ArtifactWritePolicyContext,
} from './artifact-write-policy.js';
export { parseHarnessCliCommonArgs, type HarnessCliCommonArgs } from './cli-args.js';
export {
  DEFAULT_EXTENSION_PACK_ID,
  EXTENSION_PACKS_SCHEMA_VERSION,
  ExtensionPackValidationError,
  REJECTED_FORBIDDEN_CAPABILITY_EXTENSION_PACK,
  assertExtensionPackId,
  getExtensionPackLabel,
  getExtensionPackManifestEntry,
  listExtensionPackIds,
  loadExtensionPack,
  loadExtensionPacksManifest,
  normalizeExtensionPackId,
  resolveExtensionRunSelection,
  validateExtensionPack,
  validateExtensionPacksManifest,
  type ExtensionPack,
  type ExtensionPackCapability,
  type ExtensionPackComponents,
  type ExtensionPacksManifest,
  type ExtensionPacksManifestEntry,
  type ExtensionRunSelection,
  type ExtensionScenarioPreset,
} from './extension-packs.js';
export {
  CONTENT_GOVERNANCE_SCHEMA_VERSION,
  CURRENT_CONTENT_BUNDLES,
  DEFAULT_CONTENT_GOVERNANCE_REPORT_PATH,
  governGameContent,
  governRawGameContent,
  renderContentGovernanceMarkdown,
  runContentGovernance,
  summarizeContentDiff,
  validateRawGameContent,
  writeContentGovernanceReport,
  type ContentDiffBucket,
  type ContentDiffSummary,
  type ContentGovernanceCategory,
  type ContentGovernanceDiagnostic,
  type ContentGovernanceReport,
  type ContentGovernanceSeverity,
  type ContentGovernanceSourceResult,
  type RawGameContentBundles,
  type RunContentGovernanceOptions,
} from './content-governance.js';
export {
  DEFAULT_OPTIONAL_MEDIA_REPORT_PATH,
  OPTIONAL_MEDIA_SCHEMA_VERSION,
  buildOptionalMediaAcceptanceCheck,
  buildOptionalMediaReport,
  collectOptionalMediaDiagnostics,
  listKnownOptionalMediaSceneIds,
  loadOptionalMediaManifest,
  parseOptionalMediaManifest,
  renderOptionalMediaMarkdown,
  runOptionalMediaHeadlessCheck,
  writeOptionalMediaReport,
  type OptionalMediaAssetStatus,
  type OptionalMediaDiagnostic,
  type OptionalMediaFallback,
  type OptionalMediaFallbackMode,
  type OptionalMediaHeadlessCheck,
  type OptionalMediaKind,
  type OptionalMediaManifest,
  type OptionalMediaPresentation,
  type OptionalMediaReport,
  type OptionalMediaResolvedPresentation,
  type OptionalMediaSeverity,
} from './optional-media.js';
export {
  buildArtifactBasename,
  buildReviewRelativePath,
  buildScorecardRelativePath,
  buildTraceRelativePath,
  savePlaythroughArtifacts,
  savePlaythroughReview,
  ReviewValidationError,
  type SavePlaythroughArtifactOptions,
} from './artifacts.js';
export {
  buildReviewMarkdownRelativePath,
  enrichPlaythroughReview,
  renderReviewMarkdown,
} from './review-report.js';
export {
  assertValidPlaythroughReview,
  collectReviewValidationDiagnostics,
  formatReviewValidationMessage,
  isReviewStructurallyUsable,
  type ReviewValidationDiagnostic,
  type ReviewValidationDiagnosticCategory,
  type ReviewValidationResult,
} from './review-validation.js';
export {
  getReviewerPersonaMetadata,
  listReviewerPersonaMetadata,
} from './reviewer-personas.js';
export {
  REVIEWER_PERSONA_IDS,
  ReviewGenerationError,
  createReviewerCritic,
  generateDeterministicReview,
  isReviewerPersona,
  isScorecardStructurallyUsable,
  isTraceStructurallyUsable,
  type PlaythroughReview,
  type ReviewEvidenceKind,
  type ReviewEvidenceQuality,
  type ReviewIssue,
  type ReviewIssueEvidence,
  type ReviewSeverity,
  type ReviewerCritic,
  type ReviewerCriticInput,
  type ReviewerCriticProvider,
  type ReviewerPersona,
  type ReviewerPersonaMetadata,
  type ReviewerScores,
} from './reviewer-client.js';
export {
  DEFAULT_DEVELOPER_TEST_COMMANDS,
  collectDeveloperTaskDiagnostics,
  DeveloperTaskValidationError,
  formatDeveloperTaskValidationMessage,
  GLOBAL_FORBIDDEN_CHANGES,
  generateDeveloperTask,
  getDeveloperTaskOutputPath,
  renderChangelogTemplate,
  renderDeveloperTaskMarkdown,
  renderPatchPlanTemplate,
  toHandoffDisplayPath,
  validateDeveloperTaskInput,
  type DeveloperTask,
  type DeveloperTaskDiagnostic,
  type DeveloperTaskDiagnosticCategory,
  type DeveloperTaskInput,
  type DeveloperTaskValidationResult,
} from './developer-workflow.js';
export {
  DEVELOPER_TASK_CLI_USAGE,
  runDeveloperTaskCli,
} from './developer-workflow-cli.js';
export {
  PATCH_PROPOSAL_SCHEMA_VERSION,
  PROTOCOL_INVARIANTS,
  PatchProposalValidationError,
  assembleStructuredPatchProposal,
  assertPatchProposalStructurallyValid,
  buildPatchProposalChangeFromIssue,
  buildPatchProposalChangesFromReview,
  collectPatchProposalDiagnostics,
  developerTaskInputFromPatchProposal,
  formatPatchProposalValidationMessage,
  getPatchProposalOutputPath,
  validatePatchProposalForDeveloperTask,
  validatePatchProposalReviewContext,
  validateStructuredPatchProposal,
  type PatchProposalAssemblyInput,
  type PatchProposalChange,
  type PatchProposalChangeEvidence,
  type PatchProposalDeveloperTaskContext,
  type PatchProposalDiagnostic,
  type PatchProposalDiagnosticCategory,
  type PatchProposalEvidenceArtifact,
  type PatchProposalEvidenceKind,
  type PatchProposalValidationResult,
  type StructuredPatchProposal,
} from './structured-patch-proposal.js';
export {
  PATCH_PROPOSAL_CLI_USAGE,
  buildPatchProposalAssemblyInput,
  runPatchProposalCli,
} from './patch-proposal-cli.js';
export {
  JSON_PATCH_SCHEMA_VERSION,
  JSON_PATCH_GLOBAL_ALLOWED_SURFACES,
  JsonPatchValidationError,
  applyDeterministicJsonPatch,
  assertJsonPatchStructurallyValid,
  collectJsonPatchDiagnostics,
  formatJsonPatchValidationMessage,
  getJsonPatchAuditLogPath,
  getJsonPatchReportPath,
  getJsonPatchRollbackDir,
  isGloballyAllowedPatchTarget,
  parseJsonPointer,
  pathMatchesAllowedPrefix,
  validateDeterministicJsonPatch,
  type ApplyDeterministicJsonPatchOptions,
  type DeterministicJsonPatch,
  type JsonPatchApplicationReport,
  type JsonPatchDiagnostic,
  type JsonPatchDiagnosticCategory,
  type JsonPatchFileSummary,
  type JsonPatchMode,
  type JsonPatchOperation,
  type JsonPatchOperationKind,
  type JsonPatchValidationResult,
} from './deterministic-json-patch.js';
export {
  JSON_PATCH_CLI_USAGE,
  runJsonPatchCli,
} from './json-patch-cli.js';
export {
  DEFAULT_AUDIT_FORBIDDEN_ACTIONS,
  DEFAULT_CONTEXT_EXCLUSIONS,
  DEFAULT_FORBIDDEN_CONTEXT_PATHS,
  DEFAULT_IMPLEMENTATION_FORBIDDEN_ACTIONS,
  WORKTREE_RESULT_SUMMARY_SCHEMA_VERSION,
  WORKTREE_TASK_BUNDLE_SCHEMA_VERSION,
  WorktreeTaskValidationError,
  buildEmptyWorktreeResultSummary,
  buildWorktreeAuditorTaskBundle,
  buildWorktreeImplementationTaskBundle,
  buildWorktreeTaskBundleFromPhase,
  collectWorktreeResultSummaryDiagnostics,
  collectWorktreeTaskDiagnostics,
  formatWorktreeTaskValidationMessage,
  getWorktreeResultSummaryOutputPath,
  getWorktreeTaskBundleOutputPath,
  inferOverallResultStatus,
  normalizeWorktreeResultSummary,
  validateWorktreeResultSummary,
  validateWorktreeTaskBundle,
  type WorktreeAuditorTaskBundle,
  type WorktreeCheckStatus,
  type WorktreeCommandCheck,
  type WorktreeDiffSummary,
  type WorktreeEvidenceArtifact,
  type WorktreeEvidenceKind,
  type WorktreeImplementationTaskBundle,
  type WorktreeResultSummary,
  type WorktreeTaskBundle,
  type WorktreeTaskDiagnostic,
  type WorktreeTaskDiagnosticCategory,
  type WorktreeTaskKind,
  type WorktreeTaskValidationResult,
} from './worktree-agent-orchestration.js';
export {
  WORKTREE_AGENT_CLI_USAGE as WORKTREE_TASK_CLI_USAGE,
  handleWorktreeAgentCliError,
  runWorktreeAgentCli,
} from './worktree-agent-cli.js';
export {
  LOOP_COORDINATOR_CHECKPOINT_SCHEMA_VERSION,
  LOOP_COORDINATOR_SCHEMA_VERSION,
  LOOP_COORDINATOR_STEP_ORDER,
  assessLoopIteration,
  buildLoopCoordinatorCheckpoint,
  buildLoopCoordinatorLoopId,
  getLoopCoordinatorCheckpointPath,
  getLoopCoordinatorRunbookPath,
  renderLoopCoordinatorRunbook,
  writeLoopCoordinatorArtifacts,
  type LoopCoordinatorAssessment,
  type LoopCoordinatorCheckpoint,
  type LoopCoordinatorGovernance,
  type LoopCoordinatorOutcome,
  type LoopCoordinatorStep,
  type LoopCoordinatorStepId,
  type LoopCoordinatorValidationPreview,
  type LoopStepStatus,
} from './loop-coordinator.js';
export {
  LOOP_COORDINATOR_CLI_USAGE,
  handleLoopCoordinatorCliError,
  runLoopCoordinatorCli,
} from './loop-coordinator-cli.js';
export {
  ACCEPTANCE_CHECK_STATUSES,
  COMMAND_CHECK_IDS,
  FORBIDDEN_MVP_FEATURES,
  evaluateAcceptanceGate,
  parseCommandStatusArg,
  renderAcceptanceMarkdown,
  writeAcceptanceReport,
  type AcceptanceCheck,
  type AcceptanceCheckStatus,
  type AcceptanceGateInput,
  type AcceptanceGateResult,
  type CommandCheckId,
  type CommandCheckStatus,
} from './acceptance-gate.js';
export {
  DEMO_LOOP_VERSIONS,
  parseDemoLoopArgs,
  parseDemoLoopVersionsArg,
  runDemoLoop,
  type DemoLoopComparisonResult,
  type DemoLoopOptions,
  type DemoLoopResult,
  type DemoLoopVersionResult,
  type DemoLoopVersionStatus,
} from './demo-loop.js';
export {
  buildComparisonArtifactBasename,
  buildComparisonRelativePaths,
  buildProposedChangesFromReview,
  buildReviewerDrivenHandoffInput,
  loadVersionReviewAndScorecard,
  renderComparisonMarkdown,
  writeImplementedVersionMarkdown,
  writeReviewerDrivenHandoff,
  writeVersionComparisonArtifacts,
} from './demo-loop-handoff.js';
export {
  listChallengeModeIds,
  CHALLENGE_MODES_SCHEMA_VERSION,
  DEFAULT_CHALLENGE_MODE_ID,
  assertChallengeModeId,
  getChallengeModePreset,
  loadChallengeModes,
  mergeGameConfig,
  normalizeChallengeModeId,
  resolveGameConfigForRun as resolveChallengeGameConfigForRun,
  type ChallengeModePreset,
  type ChallengeModesContentBundle,
} from '../game/challenge-modes.js';
export {
  SCENARIO_PACKS_SCHEMA_VERSION,
  DEFAULT_SCENARIO_PACK_ID,
  assertScenarioPackId,
  getGameContentForRun,
  getScenarioPackLabel,
  getScenarioPackManifestEntry,
  listScenarioPackIds,
  loadScenarioPackContent,
  loadScenarioPacksManifest,
  mergeScenarioPackContent,
  normalizeScenarioPackId,
  resolveGameConfigForRun,
  validateScenarioPackContentOverlay,
  validateScenarioPacksManifest,
  type ScenarioPackManifestEntry,
  type ScenarioPacksManifest,
} from '../game/scenario-packs.js';
export {
  DEMO_VERSION_IDS,
  VERSION_PROFILES,
  getVersionProfile,
  isDemoVersionId,
  isDemoVersionImplemented,
  resolveGameConfigForVersion,
  type DemoVersionId,
  type VersionProfile,
} from '../game/version-profiles.js';
export {
  buildCiSmokeSpecs,
  DEFAULT_CI_SMOKE_VERSION,
  runCiSmoke,
  type CiSmokeFailedRun,
  type CiSmokeResult,
  type CiSmokeRunSpec,
} from './ci-smoke.js';
export {
  discoverVersionsWithAcceptanceEvidence,
  verifyAcceptanceEvidence,
  versionHasAcceptanceEvidence,
  type AcceptanceEvidenceCheckResult,
  type AcceptanceEvidenceVersionResult,
} from './acceptance-evidence-check.js';
export {
  validateVersionEvidenceIntegrity,
  type EvidenceIntegrityArtifactKind,
  type EvidenceIntegrityDiagnostic,
  type EvidenceIntegrityDiagnosticCode,
  type EvidenceIntegrityResult,
} from './evidence-integrity.js';
export { runRepoChecks, type RepoChecksResult } from './repo-checks.js';
export {
  TRACE_REPLAY_REPORT_SCHEMA_VERSION,
  TraceReplayValidationError,
  assertTraceFileUnchanged,
  assertTraceReplayable,
  buildTraceReplayInspectOutput,
  buildTraceReplayReport,
  collectTraceReplayDiagnostics,
  diffStateSummaries,
  formatReplayStep,
  formatReexecuteSummary,
  formatTraceReplayHeader,
  formatTraceReplayValidationMessage,
  loadScorecardFromFile,
  loadTraceFromFile,
  parseTraceJson,
  readTraceFileSnapshot,
  reexecuteTrace,
  renderTraceReplayReportMarkdown,
  resolveScorecardForReplay,
  writeTraceReplayReport,
  type BuildTraceReplayInspectOptions,
  type FormatReplayStepOptions,
  type StateSummaryDeltaLine,
  type TraceReplayDiagnostic,
  type TraceReplayDiagnosticCategory,
  type TraceReplayReport,
  type TraceReplayValidationResult,
  type TraceReexecuteMismatch,
  type TraceReexecuteResult,
} from './trace-replay.js';
export {
  TRACE_REPLAY_CLI_USAGE,
  parseTraceReplayCliArgs,
  runTraceReplayCli,
  type TraceReplayCliMode,
} from './trace-replay-cli.js';
export {
  BALANCE_ANALYTICS_REPORT_PATH,
  BALANCE_ANALYTICS_SCHEMA_VERSION,
  BALANCE_LEADERBOARD_PATH,
  buildBalanceAnalyticsReport,
  buildBalanceLeaderboard,
  writeBalanceAnalyticsArtifacts,
  type BalanceAnalyticsCohort,
  type BalanceAnalyticsProblemRun,
  type BalanceAnalyticsReport,
  type BalanceAnalyticsVersionDelta,
  type BalanceLeaderboardEntry,
  type BalanceVersionAnalytics,
  type BuildBalanceAnalyticsOptions,
  type WriteBalanceAnalyticsOptions,
} from './balance-analytics.js';
export {
  BALANCE_ANALYTICS_CLI_USAGE,
  parseBalanceAnalyticsCliArgs,
  runBalanceAnalyticsCli,
  type BalanceAnalyticsCliIo,
} from './balance-analytics-cli.js';
export {
  DEFAULT_LONGITUDINAL_BENCHMARK_PATH,
  LONGITUDINAL_BENCHMARK_SCHEMA_VERSION,
  buildLongitudinalBenchmarkReport,
  writeLongitudinalBenchmarkReport,
  type BuildLongitudinalBenchmarkOptions,
  type LongitudinalAdjacentComparison,
  type LongitudinalBenchmarkReport,
  type LongitudinalEvidenceState,
  type LongitudinalMetricComparison,
  type LongitudinalMetricSource,
  type LongitudinalTrendLabel,
  type LongitudinalVersionSummary,
} from './longitudinal-benchmark.js';
export {
  LONGITUDINAL_BENCHMARK_CLI_USAGE,
  parseLongitudinalBenchmarkCliArgs,
  runLongitudinalBenchmarkCli,
  type LongitudinalBenchmarkCliIo,
} from './longitudinal-benchmark-cli.js';
export {
  VERSION_ARTIFACT_DIRS,
  VERSION_ID_PATTERN,
  VERSION_MARKDOWN_FILES,
  buildVersionSummaryRelativePath,
  compareVersions,
  ensureVersionFolder,
  getDefaultVersionRuns,
  getVersionPaths,
  persistVersionComparison,
  persistVersionSummary,
  runVersion,
  summarizeVersion,
  validateVersionId,
  type ArtifactCoverage,
  type EnsureVersionResult,
  type MetricDelta,
  type VersionArtifactDir,
  type VersionComparison,
  type VersionMarkdownFile,
  type VersionPaths,
  type VersionRunOutput,
  type VersionRunResult,
  type PersistVersionComparisonOptions,
  type PersistVersionSummaryOptions,
  type RunVersionOptions,
  type VersionRunSpec,
  type VersionSummary,
  type VersionSummaryRun,
} from './version-loop.js';
export {
  DEFAULT_RESTRICTED_AGENT_COMMAND_REGISTRY,
  RESTRICTED_AGENT_ACTIONS,
  RESTRICTED_AGENT_EVIDENCE_SCHEMA_VERSION,
  RESTRICTED_AGENT_PATCH_KINDS,
  RESTRICTED_AGENT_SCHEMA_VERSION,
  buildRestrictedAgentEvidenceRecord,
  isRestrictedAgentAction,
  isRestrictedAgentPatchKind,
  looksLikeRawShellCommand,
  validateRestrictedAgentModelResponse,
  validateRestrictedAgentRequestedChecks,
  type RestrictedAgentAction,
  type RestrictedAgentAvailableCommand,
  type RestrictedAgentBlocker,
  type RestrictedAgentCommandDefinition,
  type RestrictedAgentCommandRegistry,
  type RestrictedAgentEvidenceDecision,
  type RestrictedAgentEvidenceRecord,
  type RestrictedAgentModelResponse,
  type RestrictedAgentPatchIntent,
  type RestrictedAgentPatchKind,
  type RestrictedAgentResponseValidationOptions,
  type RestrictedAgentTurnInput,
  type RestrictedAgentValidationCategory,
  type RestrictedAgentValidationDiagnostic,
  type RestrictedAgentValidationResult,
} from './restricted-agent/index.js';
